from .medicoSerializer import MedicoSerializer
from .usuarioSerializer import UsuarioSerializer
from .pacienteSerializer import PacienteSerializer
from .histclinSerializer import HistclinSerializer
from .enferpaciSerializer import EnferpaciSerializer
from .enfermeroSerializer import EnfermeroSerializer
