from .medicoSerializer import MedicoSerializer
from .usuarioSerializer import UsuarioSerializer
from .pacienteSerializer import PacienteSerializer
from .histclinSerializer import HistclinSerializer
from .enfermeroSerializer import EnfermeroSerializer
from .asignar_med_enfserializer import Asignar_med_enfSerializer