from .userview import UsuarioListView, UsuarioRetrieveUpdateDeleteView
from .medicoview import MedicoListCreateView, MedicoRetrieveUpdateView
from .pacienteview import PacienteListCreateView, PacienteRetrieveUpdateView
from .histclinview import HistclinListCreateView, HistclinRetrieveUpdateView
from .enferpaciview import EnferpaciListView
from .enfermeroview import EnfermeroListCreateView, EnfermeroRetrieveUpdateView
