from .userview import UsuarioListView, UsuarioRetrieveUpdateDeleteView
from .medicoview import MedicoListCreateView, MedicoRetrieveUpdateView
from .pacienteview import PacienteListCreateView, PacienteRetrieveUpdateDeleteView
from .histclinview import HistclinListCreateView, HistclinRetrieveUpdateView
from .enfermeroview import EnfermeroListCreateView, EnfermeroRetrieveUpdateView
from .asignar_med_enfview import Asignar_med_enfRetrieveUpdateView